- name: Configure Cisco C890 Routers
  hosts: cisco_c890

  # 秘密情報（ansible_password や enable_password など）を含むVaultファイルを読み込み
  vars_files:
    - ../inventory/group_vars/cisco_c890_vault.yml

  gather_facts: no

  tasks:
    - name: Include common config
      include_role:
        name: common

    - name: Configure VLAN
      include_role:
        name: vlan

    - name: Configure interfaces
      include_role:
        name: interface

    - name: Configure IP prefix-list
      include_role:
        name: ip_prefix_list

    - name: Configure route-map
      include_role:
        name: route_map

    - name: Configure BGP
      include_role:
        name: bgp
