- name: Configure Cisco routers (rt01 / rt02)
  hosts: cisco_routers
  gather_facts: no
  vars:
    loopback_ip_map:
      rt01: "1.1.1.1"
      rt02: "2.2.2.2"
    gig0_ip_map:
      rt01: "192.168.12.1"
      rt02: "192.168.12.2"
    bgp_as_map:
      rt01: "65001"
      rt02: "65002"
    bgp_neighbor_as_map:
      rt01: "65002"
      rt02: "65001"
    bgp_description_map:
      rt01: "BGP peer group to downstream routers"
      rt02: "BGP peer group to upstream routers"
    bgp_password_map:
      rt01: "045802150C2E1D1C5A"
      rt02: "060506324F41584B56"
    bgp_neighbor_ip_map:
      rt01: "192.168.12.2"
      rt02: "192.168.12.1"

  tasks:
    - name: Configure VTY lines 0 to 4
      cisco.ios.ios_config:
       lines:
        - login local
        - rotary 1
        - transport input ssh
       parents: line vty 0 4
       save_when: modified
    - name: Configure VTY lines 5 to 15
      cisco.ios.ios_config:
        lines:
        - login local
        - rotary 1
        - transport input ssh
        parents: line vty 5 15
        save_when: modified

    - name: Set hostname
      cisco.ios.ios_config:
        lines:
          - hostname {{ inventory_hostname }}
        save_when: modified

    - name: Configure loopback interface
      cisco.ios.ios_config:
        lines:
          - interface Loopback0
          - ip address {{ loopback_ip_map[inventory_hostname] }} 255.255.255.255
        parents: interface Loopback0
        match: exact
        replace: line
        save_when: modified

    - name: Configure GigabitEthernet0 interface
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet0
          - ip address {{ gig0_ip_map[inventory_hostname] }} 255.255.255.252
          - duplex auto
          - speed auto
          - no shutdown
        parents: interface GigabitEthernet0
        match: exact
        replace: line
        save_when: modified

    - name: Create VLAN10
      cisco.ios.ios_config:
        lines:
           - vlan 10
        save_when: modified

    - name: Configure VLAN10 interface for SSH
      cisco.ios.ios_config:
        lines:
          - description "### for ssh ###"
          - ip address dhcp
        parents: interface Vlan10
        match: exact
        replace: line
        save_when: modified

- name: Configure BGP settings on rt01 and rt02
  hosts: rt01:rt02
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:

    - name: Configure BGP settings on rt01
      when: inventory_hostname == 'rt01'
      cisco.ios.ios_config:
        lines:
          - neighbor PEERS peer-group
          - neighbor PEERS remote-as 65002
          - neighbor PEERS description to-rt02
          - neighbor PEERS password 7 045802150C2E1D1C5A
          - neighbor PEERS timers 5 15
          - neighbor 192.168.12.2 peer-group PEERS
          - network 1.1.1.1 mask 255.255.255.255
          - bgp log-neighbor-changes
        parents: router bgp 65001
        save_when: modified

    - name: Configure BGP settings on rt02
      when: inventory_hostname == 'rt02'
      cisco.ios.ios_config:
        lines:
          - neighbor PEERS peer-group
          - neighbor PEERS remote-as 65001
          - neighbor PEERS description to-rt01
          - neighbor PEERS password 7 045802150C2E1D1C5A
          - neighbor PEERS timers 5 15
          - neighbor 192.168.12.1 peer-group PEERS
          - network 2.2.2.2 mask 255.255.255.255
          - bgp log-neighbor-changes
        parents: router bgp 65002
        save_when: modified
